apiVersion: v1
kind: Service
metadata:
  name: metrics-api-test-service
  namespace: mock
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-api-test-metrics-server
