serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml

    scrape_configs:
      - job_name: 'kubernetes-nodes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

      - job_name: 'keda-operator'
        metrics_path: /metrics
        scrape_interval: 15s
        scrape_timeout: 15s
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - keda-operator.keda:8080

      - job_name: 'keda-metrics-server'
        metrics_path: /metrics
        scrape_interval: 15s
        scrape_timeout: 15s
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - keda-metrics-apiserver.keda:8080

      - job_name: 'keda-admission-webhooks'
        metrics_path: /metrics
        scrape_interval: 15s
        scrape_timeout: 15s
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - keda-admission-webhooks.keda:8080

server:
  remoteWrite:
  - write_relabel_configs:
    - target_label: keda_version
      replacement: main
    # KEDA metrics used during tests and Container usage metrics
    - source_labels: [__name__]
      regex: "keda_internal_scale_loop_latency|keda_resource_totals|keda_build_info|^container_.*"
      action: keep

alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false