extraScrapeConfigs: |
  - job_name: 'keda-operator'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 15s
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - keda-operator.keda:8080
  - job_name: 'keda-metrics-server'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 15s
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - keda-metrics-apiserver.keda:8080
  - job_name: 'keda-admission-webhooks'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 15s
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - keda-admission-webhooks.keda:8080

server:
  remoteWrite:
  - write_relabel_configs:
    # KEDA metrics used during tests
    - source_labels: [__name__]
      regex: "keda_internal_scale_loop_latency|keda_resource_totals"
      action: keep
    # Container usage metrics
    - source_labels: [__name__]
      regex: "^container_.*"
      action: keep