apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metrics-api-test-so
  namespace: test-ns
spec:
  cooldownPeriod: 1
  maxReplicaCount: 2
  minReplicaCount: 0
  pollingInterval: 1
  scaleTargetRef:
    name: metrics-api-test-deployment
  triggers:
    - metadata:
        method: query
        targetValue: '1'
        url: >- 
          http://metrics-api-test-service.mock:8080/api/value
        valueLocation: value
      type: metrics-api