name: Execute performance tests
on:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:
    inputs:
      keda_version:
        description: "KEDA version to be used (it must be a valid tag)"
        required: false
        type: string

jobs:
  execute:
    name: Execute performance tests
    runs-on: ubuntu-latest
    concurrency: performance-tests
    env:
      KEDA_DOCKER_TAG: main
      KEDA_GITHUB_TAG: main
    steps:
      - uses: actions/checkout@v3

      - name: Override KEDA version
        if: ${{ inputs.keda_version }}
        uses: trevorlloydelliott/set-environment-variables@v1.0.0
        with:
          KEDA_DOCKER_TAG: ${{ inputs.keda_version }}
          KEDA_GITHUB_TAG: v${{ inputs.keda_version }}

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Get cluster context
        run: make get-cluster-context

      - name: Scale cluster
        run: make scale-node-pool
        env:
          NODE_POOL_SIZE: 3

      - name: Deploy dependencies
        run: make deploy

      - name: Execute performance tests
        run: make execute-k6
        env:
          REPO_BRANCH: ${{ github.ref_name }}

      - name: Cleanup dependencies
        run: make undeploy
        if: ${{ always() }}

      - name: Scale cluster
        if: ${{ always() }}
        run: make scale-node-pool
        env:
          NODE_POOL_SIZE: 1
