name: Execute performance tests
on:
  schedule:
    - cron:  '0 6 * * 1'
  workflow_dispatch:
    inputs:
      version:
        description: 'KEDA version to be used (it must be a valid tag)'
        required: true
        type: string

jobs:
  execute:
    name: Execute performance tests
    runs-on: ubuntu-latest
    concurrency: performance-tests
    env:
      VERSION: main
    steps:
      - uses: actions/checkout@v3

      - name: Override KEDA version
        if: ${{ inputs.version }} 
        uses: trevorlloydelliott/set-environment-variables@latest
        with:
          VERSION: ${{ inputs.version }}

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Get cluster context
        run: make get-cluster-context

      - name: Deploy dependencies
        run: make deploy

      - name: Execute performance tests
        run: make execute-k6

      - name: Cleanup dependencies
        run: make undeploy
        if: ${{ always() }}
