name: Execute performance tests
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  execute:
    name: Execute performance tests
    runs-on: ubuntu-latest
    concurrency: performance-tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Build k6 runner
        run: make generate-k6

      - name: Get cluster context
        run: make get-cluster-context

      - name: Deploy dependencies
        run: make deploy

      - name: Login in Grafana Cloud
        run: make login-k6

      - name: Execute performance tests
        run: make excute-k6

      - name: Cleanup dependencies
        run: make undeploy
