name: Execute performance tests
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  execute:
    name: Execute performance tests
    runs-on: ubuntu-latest
    concurrency: performance-tests
    steps:
      - uses: actions/checkout@v3

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Get cluster context
        run: make get-cluster-context

      - name: Deploy dependencies
        run: make deploy

      - name: Execute performance tests
        run: make execute-k6
        # TODO: We need to edit this before accepting PRs because this will fail with forks
        env:
          REPO_BRANCH: ${{ github.head_ref || github.ref_name }}

      - name: Cleanup dependencies
        run: make undeploy
        if: ${{ always() }}
